export const FILTER_ACTIONS = {
  SET_SORT_BY: "SET_SORT_BY",
  UPDATE_SELECTED_SIZES: "UPDATE_SELECTED_SIZES",
  UPDATE_SELECTED_BRANDS: "UPDATE_SELECTED_BRANDS",
  UPDATE_SELECTED_GENDERS: "UPDATE_SELECTED_GENDERS",
  RESET_FILTER: "RESET_FILTER"
};
